def client = "54.175.161.116"
pipeline {
    agent { label "chef"}
	stages {
		stage('Welcome') {
			steps {
				sh 'echo Starting Chef CICD'
			}
		}
        stage('Install ChefWorkstation') {
            steps {
                script {
                    def cdkExists = fileExists '/usr/bin/chef-client'
                    if (cdkExists) {
                        echo 'Pakckage already exist...Skipping installation'
                    }else{
			sh 'wget https://packages.chef.io/files/stable/chef-workstation/0.8.7/ubuntu/18.04/chef-workstation_0.8.7-1_amd64.deb'
			sh 'sudo dpkg -i chef-workstation_0.8.7-1_amd64.deb'
                    }
                }
            }
        }
        stage('Clone Cookbook from Git') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/salim8898/tomcat.git'
            }
        }
		stage('Maven build') {
            steps {
                sh 'mvn clean package'
            }
		}
		        stage('Nexus upload') {
            steps {
                script {
                    pom = readMavenPom file: "pom.xml";
                    filesByGlob = findFiles(glob: "target/*.${pom.packaging}");
                    artifactPath = filesByGlob[0].path;
                    nexusArtifactUploader(
                        nexusVersion: "nexus3",
                        protocol: "http",
                        nexusUrl: "salimnexus-1731739187.us-east-1.elb.amazonaws.com",
                        groupId: pom.groupId,
                        version: pom.version,
                        repository: "tomcat",
                        credentialsId: "nexus3_creds",
                        artifacts: [
                            [artifactId: pom.artifactId,
                            classifier: '',
                            file: artifactPath,
                            type: pom.packaging],
                            
                            /*[artifactId: pom.artifactId,
                            classifier: '',
                            file: "pom.xml",
                            type: "pom"]*/
                        ]
                     );
                    
                }
            }
        }
        stage('Inject Chef Starter kit and upload cookbook') {
            steps {
                withCredentials([file(credentialsId: 'chef-server-creds', variable: 'CHEFKIT')]) {
					sh 'ls -al $CHEFKIT'
					sh 'sudo unzip -o $CHEFKIT'
					sh 'ls $WORKSPACE'
					sh 'sudo rm -rf /chef-repo'
					sh 'sudo mv $WORKSPACE/chef-repo /'
					sh 'sudo mkdir -p /chef-repo/cookbooks/tomcat'
					sh 'sudo mv $WORKSPACE/* /chef-repo/cookbooks/tomcat'
                    sh "sudo knife cookbook upload tomcat --force -o /chef-repo/cookbooks -c /chef-repo/.chef/knife.rb"
                    withCredentials([sshUserPrivateKey(credentialsId: 'client-creds', keyFileVariable: 'AGENT_SSHKEY', passphraseVariable: '', usernameVariable: '')]) {
                        sh "knife bootstrap ${client} -x ubuntu -i $AGENT_SSHKEY -N ${client} --sudo --run-list 'recipe[tomcat]' --chef-license accept-silent -y -c /chef-repo/.chef/knife.rb"
                    }
                    
				    sh 'echo build has been finished'
                    //withCredentials([sshUserPrivateKey(credentialsId: 'agent-creds', keyFileVariable: 'AGENT_SSHKEY', passphraseVariable: '', usernameVariable: '')]) {
					//	sh "knife ssh 'name:client' -x salim -i $AGENT_SSHKEY 'sudo chef-client' -c $CHEFKIT/chef-repo/.chef/knife.rb"
                    //}
                }
            }
        }
		
    }
}
